### ISSUE TITLE
Trying this app with MATRICE_100 drone

### ISSUE THREAD

**Issue by ZeeshanShabbir** [InterestingWalrus/matrice_mobile#1]
Hey, I am trying to configure same code for MATRICE_100 and i was successful to connect app with flight controller but when i click on takeOff or another button it doesn't effect the drone at all. But i do get this message on raspberry pi computer it says "getDataFromMSDKCallBack, L62: Recieved mobile Data of len 19" Can help me out here? What can i do to fix this problem?

**Comment by ybabs** [comment]
Hi, you need this ROS package installed: https://github.com/InterestingWalrus/matrice_autonomy/tree/master/src
